<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Invoice {{ $invoice->invoice_number }}</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#edf0f4;color:#202c3d;font:14px Arial,sans-serif}.toolbar{max-width:1000px;margin:20px auto;display:flex;gap:12px;flex-wrap:wrap}.toolbar a,.toolbar button{padding:10px 16px;background:#3578dc;color:white;border:0;border-radius:4px;text-decoration:none;cursor:pointer}.sheet{background:white;max-width:1000px;margin:20px auto;padding:45px}header{display:flex;justify-content:space-between;gap:25px;border-bottom:1px solid #d5d9df;padding-bottom:22px}.hotel{flex:1;text-align:center}.hotel h1{font-size:25px;margin:0 0 8px}.hotel p{margin:7px 0}.meta{text-align:right;max-width:310px;overflow-wrap:anywhere}.meta h2{font-size:27px;font-weight:400;color:#8792a3;margin:0 0 12px}.bill-to{margin:22px 0 32px}.bill-to h2{font-size:22px;margin:12px 0}.bill-to p{margin:6px 0}.label{color:#6d788b}table{width:100%;border-collapse:collapse;color:#111}th,td{border:1px solid #111;padding:10px;text-align:left;overflow-wrap:anywhere}th{font-size:15px}td.description{width:45%}.number{text-align:right;white-space:nowrap}.words{border:1px solid #111;padding:17px;margin-top:20px;color:#111}.terms{margin:34px 0 22px;font-weight:bold}.payment p{margin:6px 0}.multiline{white-space:pre-line;overflow-wrap:anywhere}.balances{margin-top:14px;text-align:right}.status{margin-top:12px}thead{display:table-header-group}tr,.words,.payment{break-inside:avoid}@page{size:A4;margin:14mm}@media print{body{background:white}.toolbar{display:none}.sheet{margin:0;padding:0;max-width:none}a{color:inherit;text-decoration:none}}@media(max-width:600px){.sheet{padding:20px}header{flex-direction:column}.meta{text-align:left;max-width:none}.number{white-space:normal}th,td{padding:6px}}
</style></head><body>
<div class="toolbar"><a href="{{ route('guests.show', $invoice->guest_id) }}">Back to Guest</a><button onclick="window.print()">Print / Save PDF</button>@if($invoice->status !== 'Cancelled' && $invoice->balance_amount > 0)<a href="{{ route('payments.create', ['target_type' => 'invoice', 'target_id' => $invoice->id]) }}">Receive Payment</a>@endif</div>
<main class="sheet"><header>@if($logoUrl = \App\Models\InvoiceSetting::logoUrl($issuer['logo_path'] ?? null))<div><img src="{{ $logoUrl }}" alt="Hotel logo" style="width:110px;max-height:110px;object-fit:contain"></div>@endif<div class="hotel"><h1>{{ $issuer['name'] }}</h1>@if($issuer['tin'])<p>TIN Number {{ $issuer['tin'] }}</p>@endif<p class="multiline">{{ $issuer['address'] }}</p><p>{{ $issuer['phone'] }}</p><p>{{ $issuer['email'] }}</p></div><div class="meta"><h2>INVOICE</h2><strong>INV# {{ $invoice->invoice_number }}</strong><p><span class="label">DATE</span><br>{{ $invoice->issued_at?->format('F j, Y') }}</p>@if($invoice->due_date)<p><span class="label">DUE DATE</span><br>{{ $invoice->due_date->format('F j, Y') }}</p>@endif</div></header>
<section class="bill-to"><span class="label">BILL TO</span><h2>{{ $billTo['name'] ?? '' }}</h2>@if(!empty($billTo['tin']))<p>TIN: {{ $billTo['tin'] }}</p>@endif<p class="multiline">{{ $billTo['address'] ?? '' }}</p><p>{{ $billTo['phone'] ?? '' }}</p><p>{{ $billTo['email'] ?? '' }}</p></section>
<table><thead><tr><th>S/N</th><th>DESCRIPTION</th><th>PRICE</th><th>QTY</th><th>AMOUNT</th></tr></thead><tbody>@foreach($invoice->items as $item)<tr><td>{{ $loop->iteration }}</td><td class="description">{{ $item->description }}</td><td class="number">{{ number_format($item->unit_price, 2) }}</td><td>{{ $item->quantity }}</td><td class="number">{{ number_format($item->total_price, 2) }}</td></tr>@endforeach<tr><th colspan="4" class="number">TOTAL ({{ $issuer['currency'] }})</th><th class="number">{{ number_format($invoice->subtotal, 2) }}</th></tr></tbody></table>
<div class="words"><strong>Amount in words: </strong>{{ $amountInWords }}</div>
<div class="balances">Paid: {{ number_format($invoice->paid_amount, 2) }} &nbsp; | &nbsp; Balance: {{ number_format($invoice->balance_amount, 2) }} {{ $issuer['currency'] }}<div class="status">Status: {{ $invoice->status }}</div></div>
@if($invoice->notes)<p class="multiline">{{ $invoice->notes }}</p>@endif
<p class="terms multiline">{{ $issuer['terms'] }}</p>
<section class="payment"><h3>Payment options</h3>@if($issuer['payment_name'])<p><strong>{{ $issuer['payment_name'] }}</strong></p>@endif @if($issuer['merchant_number'])<p>Merchant# {{ $issuer['merchant_number'] }}</p>@endif @if($issuer['payment_provider'])<p>{{ $issuer['payment_provider'] }}</p>@endif
@foreach(['bank_name' => 'BANK', 'account_name' => 'ACCOUNT NAME', 'account_number' => 'ACCOUNT NUMBER', 'swift_code' => 'SWIFT CODE'] as $key => $label)@if(!empty($issuer[$key]))<p><strong>{{ $label }}:</strong> {{ $issuer[$key] }}</p>@endif @endforeach<p><strong>CURRENCY:</strong> {{ $issuer['currency'] }}</p></section>
</main></body></html>
